# Generated by Django 5.1.5 on 2025-02-11 22:08

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('cashier', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, default='', max_length=50, null=True, unique=True)),
                ('product', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_image_upload_path)),
                ('is_new', models.BooleanField(default=False)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category')),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brands.brand')),
                ('idUnit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cashier.unit')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-idCategory', 'product', 'idMarca'],
            },
        ),
    ]
