# Generated by Django 5.1.5 on 2025-02-11 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Perfil de Facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de Instagram')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de WhatsApp')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComisionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsecutivoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('codigo_autorizacion', models.CharField(max_length=20)),
                ('fecha_autorizacion', models.DateField()),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsecutivoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsecutivoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('TICKET', 'Ticket'), ('FACTURA', 'Factura')], max_length=10, unique=True)),
                ('numero_actual', models.PositiveIntegerField(default=0)),
                ('numero_inicial', models.PositiveIntegerField(default=1)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo', models.CharField(choices=[('TICKET', 'Ticket'), ('FACTURA', 'Factura')], max_length=10)),
                ('consecutivo', models.PositiveIntegerField(editable=False, unique=True)),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TR', 'Transferencia'), ('TC', 'Tarjeta de Crédito')], default='EF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MINORISTA', 'Minorista'), ('MAYORISTA', 'Mayorista'), ('PROMOCION', 'Promoción')], max_length=10)),
                ('porcentaje_aumento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_precio', models.CharField(choices=[('MINORISTA', 'Minorista'), ('MAYORISTA', 'Mayorista'), ('PROMOCION', 'Promoción')], max_length=10)),
                ('precio_original', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
    ]
