# Generated by Django 5.1.5 on 2025-02-11 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionvendedor',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('sale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.sale')),
                ('consecutivoF', models.PositiveIntegerField(editable=False, unique=True)),
                ('codigo_autorizacion', models.CharField(max_length=20)),
                ('fecha_autorizacion', models.DateField()),
            ],
            bases=('sales.sale',),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('sale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.sale')),
                ('consecutivoT', models.PositiveIntegerField(editable=False, unique=True)),
            ],
            bases=('sales.sale',),
        ),
        migrations.AddField(
            model_name='sale',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.cliente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='precioventa',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.sale'),
        ),
    ]
