# Archivo render.yaml para desplegar un proyecto Django en Render

services:
  - type: web
    name: gesinv-django-app  # Nombre del servicio web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn conf.wsgi:application  # Ajusta "myproject" al nombre de tu proyecto
    envVars:
      - key: DEBUG
        value: "False"  # Desactiva el modo debug en producción
      - key: SECRET_KEY
        value: "django-insecure--ytt)x(1(glb-fcy6*v5gbt^hv1=hlx-2)4v#^%__7xrc6#ua6"  # Asegúrate de usar una clave secreta segura
      - key: DB_NAME
        value: "gesinv_8lor"  # Nombre de la base de datos
      - key: DB_USER
        value: "gesinv"  # Usuario de la base de datos
      - key: DB_PASSWORD
        value: "et8SKoxToffSkHjKdlXPbBSqe0gO5sNa"  # Contraseña de la base de datos
      - key: DB_HOST
        value: "dpg-cumminogph6c7386h9k0-a.oregon-postgres.render.com"  # Host de la base de datos
      - key: DB_PORT
        value: "5432"  # Puerto de la base de datos
      - key: ALLOWED_HOSTS
        value: "*"  # Permite todos los hosts (ajusta esto en producción)
    instanceType: free  # Usa "free" para pruebas o "standard" para producción