# Generated by Django 5.1.5 on 2025-02-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='CatalogProduct',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
