# Generated by Django 5.1.5 on 2025-02-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('codigo_base', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Código Base')),
                ('siglas', models.CharField(blank=True, max_length=10, verbose_name='Siglas')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='categories.category', verbose_name='Categoría parent')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['-idCategory'],
            },
        ),
    ]
