# Generated by Django 5.1.5 on 2025-02-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('idBrand', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['brand'],
            },
        ),
    ]
