# Generated by Django 5.1.5 on 2025-02-15 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('catalogs', '0002_initial'),
        ('products', '0002_alter_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('idCatalog', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='catalogs/')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.brand')),
            ],
            options={
                'db_table': 'catalogs',
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('idCatalogProduct', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.catalog')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'catalog_products',
                'ordering': ['order'],
            },
        ),
    ]
