# Generated by Django 5.1.5 on 2025-02-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_catalog_catalogproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
