# Generated by Django 5.1.5 on 2025-02-15 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_alter_catalog_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='pvp',
        ),
        migrations.AddField(
            model_name='catalogproduct',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=14022025, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
