# Generated by Django 5.1.5 on 2025-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_remove_catalog_brand_remove_catalog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogproduct',
            name='pvp',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
