# Generated by Django 5.1.5 on 2025-02-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la ubicación (ej: Estante A)', max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(help_text='Código único de la ubicación (ej: EST-A)', max_length=10, unique=True, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='BajaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible')),
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Artículo')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='inventory.ubicacion', verbose_name='Ubicación de destino')),
                ('ubicacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='inventory.ubicacion', verbose_name='Ubicación de origen')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Artículo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ubicacion', verbose_name='Ubicación')),
            ],
        ),
    ]
