INSERT INTO brands (brand) VALUES
	 ('0GENERICO'),
	 ('+PERFETTA CARE'),
	 ('24K'),
	 ('3D MASSAGER'),
	 ('AAUNG'),
	 ('ABS'),
	 ('ABSOLUTE'),
	 ('ADDICT'),
	 ('ADORO'),
	 ('AGUJAS BIOMASER DE ROSCA');
INSERT INTO brands (brand) VALUES
	 ('AGUJAS UNIVERSALES'),
	 ('AGUJAS UNIVERSALES DE TATUAR Y MICROPIGMENTACION'),
	 ('ALICE'),
	 ('ALLURE'),
	 ('AMALFI'),
	 ('AMAZING SHINE'),
	 ('AMOR US'),
	 ('AMY'),
	 ('ANA BEAUTY'),
	 ('ANGIE');
INSERT INTO brands (brand) VALUES
	 ('ANJIEER'),
	 ('ANQIXIU'),
	 ('ANTONIO BANDERAS'),
	 ('AOYASIYUE'),
	 ('ARTEMIAEXTRAC'),
	 ('AS'),
	 ('AVALEIS'),
	 ('AWAN'),
	 ('AZEIDA'),
	 ('BARBER PRO');
INSERT INTO brands (brand) VALUES
	 ('BARBER SHOP'),
	 ('BARBERO'),
	 ('BEAUTIFUL NAILS'),
	 ('BEAUTY'),
	 ('BEAUTY INSTRUMENT'),
	 ('BEAUTY MODEL'),
	 ('BELL'),
	 ('BELLESRE'),
	 ('BIGGERBOWIE'),
	 ('BIO VITALY');
INSERT INTO brands (brand) VALUES
	 ('BIOMASER'),
	 ('BIOTOUCH'),
	 ('BJ BLAST'),
	 ('BLACK POWER'),
	 ('BMX'),
	 ('BODEGAS MARK 2'),
	 ('BOSHILING'),
	 ('BRITNEY SPEARS'),
	 ('BUTTERFLY'),
	 ('BYPHASSE');
INSERT INTO brands (brand) VALUES
	 ('BYSPRO'),
	 ('C&L'),
	 ('CAMTOYZ RAW'),
	 ('CECILLIA'),
	 ('CHARCOAL'),
	 ('CHARM LIMIT'),
	 ('CHARMANT'),
	 ('CHENALE'),
	 ('CHINO'),
	 ('CHIVEY');
INSERT INTO brands (brand) VALUES
	 ('CHOCOLIFE'),
	 ('CLAVIN KLEIN'),
	 ('CLEANER'),
	 ('CONNERT'),
	 ('CONTOOR KHOL'),
	 ('COQUETA''S'),
	 ('CORRUGATED'),
	 ('CREED'),
	 ('CROCODILE'),
	 ('C-SILAM');
INSERT INTO brands (brand) VALUES
	 ('CSLAB'),
	 ('CURVY'),
	 ('DH'),
	 ('DIAMOND FOIL'),
	 ('DINAMIC'),
	 ('DISAAR'),
	 ('DIY'),
	 ('DODO GIRL'),
	 ('DOUCCE'),
	 ('DR MEINAIER');
INSERT INTO brands (brand) VALUES
	 ('DRAGON RANCE'),
	 ('DRS'),
	 ('E&A'),
	 ('EASY FRENCH'),
	 ('ECCSECE'),
	 ('ENCANTO'),
	 ('EP CHEMICALS'),
	 ('ERHA 21'),
	 ('ESGIDO'),
	 ('EUFORIA');
INSERT INTO brands (brand) VALUES
	 ('EURO DENTAL'),
	 ('EXPERENCE INCREDIBLY'),
	 ('EXPOSSED LABC'),
	 ('EXTREME BEAUT'),
	 ('EYEBELLE'),
	 ('EYEBROW CREAM'),
	 ('EYEBROWN'),
	 ('EYELA'),
	 ('EYELINER'),
	 ('EZFIOW');
INSERT INTO brands (brand) VALUES
	 ('FA LING'),
	 ('FACE WASH'),
	 ('FAFULA'),
	 ('FAIR'),
	 ('FAMISOO'),
	 ('FANG ZI'),
	 ('FANTASIAS ARIEL'),
	 ('FANTASIAS RUBY'),
	 ('FARCLOSE'),
	 ('FASHION');
INSERT INTO brands (brand) VALUES
	 ('FASHION DE L'),
	 ('FASHION JEWELLY'),
	 ('FASHION NAIL'),
	 ('FASMC'),
	 ('FAWY'),
	 ('FAYUAN'),
	 ('FEBBLE'),
	 ('FEMALE MASTURBATION'),
	 ('FEMME FATALE'),
	 ('FENGPASS');
INSERT INTO brands (brand) VALUES
	 ('FENTY'),
	 ('FIT WE'),
	 ('FLATBACK'),
	 ('FLAVOR SX'),
	 ('FLAWLESS'),
	 ('FLOWERS'),
	 ('FOR HER'),
	 ('FOR ME ONLY'),
	 ('FOR MEN'),
	 ('FOREVER');
INSERT INTO brands (brand) VALUES
	 ('FORGET ME'),
	 ('FR'),
	 ('FRESH'),
	 ('FRUIT OF THE WOKALI'),
	 ('FUZE'),
	 ('G BEAUTY'),
	 ('GALENCO'),
	 ('GARNIER'),
	 ('GEIMEI'),
	 ('GENERATION');
INSERT INTO brands (brand) VALUES
	 ('GENERICO'),
	 ('GERALDY'),
	 ('GIANNI ROTTI'),
	 ('GIVENCHY'),
	 ('GLAM BEAUTY'),
	 ('GLAM NAILS'),
	 ('GLOBALNAIL'),
	 ('GLOSS NUDE'),
	 ('GNAILS'),
	 ('GND');
INSERT INTO brands (brand) VALUES
	 ('GNDG'),
	 ('GOLD FINGER'),
	 ('GREEN TEA'),
	 ('GREYMA'),
	 ('GUANJING'),
	 ('GUCCI'),
	 ('GUESS'),
	 ('GUILLOTINA'),
	 ('GULF GIRL'),
	 ('GUO JI FENG');
INSERT INTO brands (brand) VALUES
	 ('GWD'),
	 ('HAIR CLIPPER'),
	 ('HAN KAI'),
	 ('HAND SANITIZER'),
	 ('HANZHIKAI'),
	 ('HAR COLOR'),
	 ('HEAD SHOULDERS'),
	 ('HEALTH'),
	 ('HEALTHY'),
	 ('HEAUTHY');
INSERT INTO brands (brand) VALUES
	 ('HEAVEN'),
	 ('HELLO KITTY'),
	 ('HENNA'),
	 ('HIDRA COLOR'),
	 ('HIDROXON'),
	 ('HOLIDAYS'),
	 ('HONEY NAIL'),
	 ('HOT HUEZ'),
	 ('HUASHI'),
	 ('HUASISI');
INSERT INTO brands (brand) VALUES
	 ('HUDA'),
	 ('HUDA BEAUTY'),
	 ('HUDABEKITY'),
	 ('HUDAMOJI'),
	 ('HUGO BOSS'),
	 ('HUXIA'),
	 ('HUXIA BEAUTY'),
	 ('HUXIABEAUTY'),
	 ('ICONSIGN'),
	 ('IMAN OF NOBLE');
INSERT INTO brands (brand) VALUES
	 ('INGESA'),
	 ('INK MIXER'),
	 ('INTERBEL'),
	 ('ISABELLA'),
	 ('ISSUE'),
	 ('ITALIA'),
	 ('ITALIA DELUXE'),
	 ('ITIS BEAUTY'),
	 ('IVENTAGE'),
	 ('JACLYN');
INSERT INTO brands (brand) VALUES
	 ('JAGUAR'),
	 ('JESEE'),
	 ('JEWEL MANIKURE'),
	 ('JEWELRY STORAGE'),
	 ('JIANHUI'),
	 ('JIN DIE'),
	 ('JINCHINIAO'),
	 ('JLASH'),
	 ('JOHNSONS'),
	 ('JUMBO');
INSERT INTO brands (brand) VALUES
	 ('KAIO'),
	 ('KAIZE'),
	 ('KAIZER'),
	 ('KAJAL'),
	 ('KALIYA'),
	 ('KALIYA BEAUTY'),
	 ('KAM DFLY'),
	 ('KARITE'),
	 ('KATIVA'),
	 ('KEEP COLOR');
INSERT INTO brands (brand) VALUES
	 ('KEKE'),
	 ('KINGJUN'),
	 ('KISSBEAUTY'),
	 ('KISSCROW'),
	 ('KIYOME'),
	 ('KL'),
	 ('KLEANCOLOR'),
	 ('KNAIL'),
	 ('KOLINSKY'),
	 ('KONSUNG');
INSERT INTO brands (brand) VALUES
	 ('KRISBEAUTY'),
	 ('KRISSCROWN'),
	 ('KUUL'),
	 ('KYLIE'),
	 ('L&D'),
	 ('L. A. COLORS'),
	 ('L.A COLORS '),
	 ('L.A GIRL'),
	 ('LAIWANG'),
	 ('LALA''S');
INSERT INTO brands (brand) VALUES
	 ('LANCE''S COCK'),
	 ('LANCOME'),
	 ('LANELL'),
	 ('LEAUVIVE'),
	 ('LECHE PAL PELO'),
	 ('LEHIT'),
	 ('LEI NA'),
	 ('LEMAY'),
	 ('LETVAS'),
	 ('LEVEL BEAUTY');
INSERT INTO brands (brand) VALUES
	 ('LF'),
	 ('LIANG'),
	 ('LICOL'),
	 ('LIDIAN'),
	 ('LILI PINK'),
	 ('LILO'),
	 ('LILY BREEZE'),
	 ('LINA'),
	 ('LINDA'),
	 ('LINGE');
INSERT INTO brands (brand) VALUES
	 ('LINGPAN'),
	 ('LINUS'),
	 ('LIP BALM'),
	 ('LIPSTICK SHELF'),
	 ('LIRA'),
	 ('LIRU'),
	 ('LISSIA'),
	 ('LM SELECTED'),
	 ('L''MAR'),
	 ('LOLA');
INSERT INTO brands (brand) VALUES
	 ('LONDON'),
	 ('LOREAL'),
	 ('LOVE'),
	 ('LSH'),
	 ('LUBRIDERM'),
	 ('LUET'),
	 ('LUKASI'),
	 ('LUX MI'),
	 ('M&CO'),
	 ('MAC');
INSERT INTO brands (brand) VALUES
	 ('MAC LIGHTFUL'),
	 ('MACALLUR'),
	 ('MADE FOR YOU'),
	 ('MAGIC'),
	 ('MAGIK'),
	 ('MAKE UP'),
	 ('MAKEUP'),
	 ('MAKEY PLUSS'),
	 ('MALIBU'),
	 ('MARIA JOSE');
INSERT INTO brands (brand) VALUES
	 ('MARIPOSA'),
	 ('MARLIOU'),
	 ('MARTINA'),
	 ('MASGLO'),
	 ('MASHE'),
	 ('MASTERNAILS'),
	 ('MASTOR'),
	 ('MAXE'),
	 ('MAXYBELT'),
	 ('MAYBELLINE');
INSERT INTO brands (brand) VALUES
	 ('MAYFIELD'),
	 ('MECOW'),
	 ('MEFAPO'),
	 ('MEILINDER'),
	 ('MELODY'),
	 ('MERCEDES'),
	 ('MERCURY'),
	 ('MERHEJE'),
	 ('MERRY'),
	 ('MERRYCOLOR');
INSERT INTO brands (brand) VALUES
	 ('METAL CARE'),
	 ('MIA SECRET'),
	 ('MICKEY'),
	 ('MILAI'),
	 ('MILK'),
	 ('MILLENIUM'),
	 ('MILLION'),
	 ('MILLY'),
	 ('MINI FAN'),
	 ('MINNIE');
INSERT INTO brands (brand) VALUES
	 ('MIRROR'),
	 ('MISS ADORO'),
	 ('MISS BEAUTY'),
	 ('MISS DEMI'),
	 ('MISS KALIYA'),
	 ('MISS KAREENA'),
	 ('MISS LOU'),
	 ('MISS NANA'),
	 ('MISS SQUILD'),
	 ('MISS SUMMER');
INSERT INTO brands (brand) VALUES
	 ('MISS VANESSA'),
	 ('MISSYAHO'),
	 ('MITHRA'),
	 ('MIXUEER'),
	 ('MK'),
	 ('MOC ALLURE'),
	 ('MOC MALLURE'),
	 ('MOFAJANG'),
	 ('MOLLIE'),
	 ('MOMING BUD');
INSERT INTO brands (brand) VALUES
	 ('MURPHY'),
	 ('MUSHEE'),
	 ('MYLIFE'),
	 ('MYM'),
	 ('NABI'),
	 ('NAGARAKU'),
	 ('NAIL'),
	 ('NAIL AAT'),
	 ('NAIL ART'),
	 ('NAIL DECORATIONS');
INSERT INTO brands (brand) VALUES
	 ('NAIL SUPPLIES'),
	 ('NAILEN'),
	 ('NAKED'),
	 ('NANO'),
	 ('NAPROLAB'),
	 ('NATALY'),
	 ('NATIVO''S'),
	 ('NATURAL HAIR'),
	 ('NATURE`S BEE'),
	 ('NAUGHTY');
INSERT INTO brands (brand) VALUES
	 ('NAVINA'),
	 ('NEATCELL'),
	 ('NEICHA'),
	 ('NEUTROGENA'),
	 ('NEVADA'),
	 ('NEW FASHION'),
	 ('NEW QUALITY'),
	 ('NEW STETIC'),
	 ('NINE'),
	 ('NIVEA');
INSERT INTO brands (brand) VALUES
	 ('NML'),
	 ('NO NIX'),
	 ('NOA'),
	 ('NOBLE'),
	 ('NOVA'),
	 ('NUBELLE'),
	 ('NUDE NEW'),
	 ('NUDES'),
	 ('OLALI'),
	 ('ONGEA');
INSERT INTO brands (brand) VALUES
	 ('OPALESCENT'),
	 ('OPI'),
	 ('ORANOT'),
	 ('ORGANICA'),
	 ('ORGANIX'),
	 ('OSITO'),
	 ('OSSION'),
	 ('OTTIE'),
	 ('P&W'),
	 ('P.C.D');
INSERT INTO brands (brand) VALUES
	 ('PAIE'),
	 ('PAINSTOPPERS'),
	 ('PALLET HOT WAX'),
	 ('PANDORA'),
	 ('PANTENE'),
	 ('PAORA'),
	 ('PARIS HILTON'),
	 ('PARMISS'),
	 ('PEGADITO'),
	 ('PENDIENTE');
INSERT INTO brands (brand) VALUES
	 ('PEPA'),
	 ('PERFECT EYEBROWS'),
	 ('PERMABLEND'),
	 ('PERMANENT BEAUTY'),
	 ('PESTAÑIL'),
	 ('PETTRY COWRY'),
	 ('PIBAMY'),
	 ('PILATEN'),
	 ('PILI'),
	 ('PINCELLE');
INSERT INTO brands (brand) VALUES
	 ('PINK'),
	 ('PINK KEY'),
	 ('PINKEES'),
	 ('PINL'),
	 ('PLACENTA LIFE'),
	 ('PLACER'),
	 ('PLANTE PMU'),
	 ('PLAST PLAN'),
	 ('PLATEN'),
	 ('PLIUG NAIL');
INSERT INTO brands (brand) VALUES
	 ('PMU MACHINE'),
	 ('POLKA'),
	 ('PONDS'),
	 ('POP ICON'),
	 ('PORTA CUPS ACRILICO'),
	 ('PORTA CUPS METAL'),
	 ('POWDER FREE'),
	 ('POWER'),
	 ('POWERS X'),
	 ('PR CROCODILE');
INSERT INTO brands (brand) VALUES
	 ('PR KELI BEAUTY'),
	 ('PR NECK RUFFLES'),
	 ('PR PRO WAX'),
	 ('PRECIOSAS'),
	 ('PRECISION LIFE'),
	 ('PREMIUM'),
	 ('PRETTY COWRY'),
	 ('PRIMS'),
	 ('PRLUX'),
	 ('PROFESSIONAL');
INSERT INTO brands (brand) VALUES
	 ('PROFESSIONAL SAFTY'),
	 ('PROFUSSION'),
	 ('PROKPIL'),
	 ('PROLUX'),
	 ('PRO-WAX'),
	 ('PRO-WAX100'),
	 ('PULIDOR'),
	 ('PURE'),
	 ('PW'),
	 ('PX LOOK');
INSERT INTO brands (brand) VALUES
	 ('QIAOYIME'),
	 ('QILIANG'),
	 ('QINGMEI'),
	 ('QUANLILI'),
	 ('RADIANT'),
	 ('RANEE'),
	 ('RAQUEL'),
	 ('RASPBERRY'),
	 ('RBORON'),
	 ('REDBERRY');
INSERT INTO brands (brand) VALUES
	 ('RENE CHARDON'),
	 ('REPLICA'),
	 ('RHINO BLACK'),
	 ('RODHER'),
	 ('ROLLER'),
	 ('ROMANKY'),
	 ('ROMANTIC BEAUTY'),
	 ('ROMANTIC QUEEN'),
	 ('ROMWE'),
	 ('ROTARY');
INSERT INTO brands (brand) VALUES
	 ('ROVI'),
	 ('RUBBER'),
	 ('RUBY FACE'),
	 ('RUCHA'),
	 ('S.F.R'),
	 ('S.F.R COLOR'),
	 ('S.F.R COLORS'),
	 ('SABBUHA'),
	 ('SAGITARIU''S'),
	 ('SALON IN');
INSERT INTO brands (brand) VALUES
	 ('SAMY'),
	 ('SANA'),
	 ('SANDRY'),
	 ('SANDY'),
	 ('SANO'),
	 ('SAPHIR'),
	 ('SAPO'),
	 ('SARA NAIL'),
	 ('SARKI SWEEKIE'),
	 ('SAS');
INSERT INTO brands (brand) VALUES
	 ('SAVITAL'),
	 ('SCHWARZKOPF'),
	 ('SEDAL'),
	 ('SEN INTIMO'),
	 ('SERSANLOVE'),
	 ('SEVEN'),
	 ('SEVENCOOL'),
	 ('SEXT EYES'),
	 ('SEYOR'),
	 ('SFR COLOR');
INSERT INTO brands (brand) VALUES
	 ('SHAKIRA'),
	 ('SHAQUINUO'),
	 ('SHARP'),
	 ('SHEDOES'),
	 ('SHIDI SHANGPIN'),
	 ('SHINING'),
	 ('SHOOTING'),
	 ('SHU MEI'),
	 ('SHY BEAM'),
	 ('SKAFE');
INSERT INTO brands (brand) VALUES
	 ('SKALA'),
	 ('SKIN CARE'),
	 ('SKIN CLEANER'),
	 ('SKLV'),
	 ('SKULL'),
	 ('SKY HIGH'),
	 ('SMI'),
	 ('SMIEL'),
	 ('SMOOTH FEET'),
	 ('SOFIA VERGARA');
INSERT INTO brands (brand) VALUES
	 ('SOLINGEN'),
	 ('SOLO'),
	 ('SONAR'),
	 ('SONIA VEGA'),
	 ('SP GLOVES'),
	 ('SPLINT'),
	 ('SPONGE'),
	 ('SQUARE'),
	 ('SQUARE NATURAL'),
	 ('SSS');
INSERT INTO brands (brand) VALUES
	 ('ST.IVES'),
	 ('STAMPING NAILS'),
	 ('STAR HAIR'),
	 ('STAR TOOLS'),
	 ('STARLINER'),
	 ('STARRY'),
	 ('STARS COLORS'),
	 ('STEFANIS'),
	 ('STELLA'),
	 ('STORAGE');
INSERT INTO brands (brand) VALUES
	 ('SUAVECITO'),
	 ('SUCKING'),
	 ('SUGESTIVE'),
	 ('SUMMER'),
	 ('SUN'),
	 ('SUNMINI'),
	 ('SUPER MAN'),
	 ('SUPER NAIL'),
	 ('SUPER PRO'),
	 ('SUPERNAIL');
INSERT INTO brands (brand) VALUES
	 ('SVENCOOL'),
	 ('SWABS'),
	 ('TAFT'),
	 ('TAPER BLADES'),
	 ('TDJ'),
	 ('TH'),
	 ('THE BARBERIA'),
	 ('THE ORDINARY'),
	 ('THREE AVANTAGES'),
	 ('THUNDERLOCK');
INSERT INTO brands (brand) VALUES
	 ('THUNDERLORD POWER'),
	 ('THYMS'),
	 ('TIAN HO'),
	 ('TICTAC'),
	 ('TIMOON'),
	 ('TINADAVIES'),
	 ('TINKLE'),
	 ('TKTX'),
	 ('TOKYO'),
	 ('TOMMY');
INSERT INTO brands (brand) VALUES
	 ('TOO FACED'),
	 ('TOPPIK'),
	 ('TOUCHME'),
	 ('TREE LIFE'),
	 ('TRIMS'),
	 ('TROPICAL'),
	 ('TSN'),
	 ('TUMDERLOCK AGUJAS UNIVERSALES X 20'),
	 ('UNICORNIO'),
	 ('UNITED COLORS');
INSERT INTO brands (brand) VALUES
	 ('UNO'),
	 ('UOVOPENS'),
	 ('URBAN'),
	 ('URBAN MAKEUP'),
	 ('URBANUS'),
	 ('USA'),
	 ('USHAS'),
	 ('V.V.LOVE'),
	 ('VANDUX'),
	 ('VANYTIC');
INSERT INTO brands (brand) VALUES
	 ('VENUS VQUEEN'),
	 ('VERA'),
	 ('VEZE'),
	 ('VICKY NAIL'),
	 ('VICTORIA SECRET'),
	 ('VICTORIA''S SECRET'),
	 ('VICTORINOX'),
	 ('VINILADY'),
	 ('VINY LADY'),
	 ('VITAMAC');
INSERT INTO brands (brand) VALUES
	 ('VIVA2'),
	 ('VIZIO'),
	 ('VOGUE'),
	 ('VS REPLICA'),
	 ('VV'),
	 ('WAER'),
	 ('WAS BEANS'),
	 ('WAX'),
	 ('WENDY'),
	 ('WERHL');
INSERT INTO brands (brand) VALUES
	 ('WET N WILD'),
	 ('WIG CAP'),
	 ('WOKALI'),
	 ('WORLD COLOR'),
	 ('WOW'),
	 ('XIUYA'),
	 ('XKJ'),
	 ('XXOO'),
	 ('YACHAN'),
	 ('YAFANNI');
INSERT INTO brands (brand) VALUES
	 ('YAMEI'),
	 ('YAXI BEAUTY'),
	 ('YCID'),
	 ('YDBY'),
	 ('YEMIX'),
	 ('YH'),
	 ('YH BEJA'),
	 ('YIGAN'),
	 ('YIQIAN'),
	 ('YIQUIAN');
INSERT INTO brands (brand) VALUES
	 ('YM'),
	 ('YYNAIL'),
	 ('ZESGOOD'),
	 ('ZINGER'),
	 ('ZIYI'),
	 ('ZOLA'),
	 ('ZONA V'),
	 ('ZORELA'),
	 ('ZSC'),
	 ('ZZAM');
