# Generated by Django 5.1.5 on 2025-02-11 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de costo')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de venta')),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Costo total')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Artículo')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Artículo')),
            ],
        ),
    ]
