# Generated by Django 5.1.5 on 2025-02-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('idCashier', models.AutoField(primary_key=True, serialize=False)),
                ('cashier', models.CharField(max_length=255)),
                ('serialNumber', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'cashiers',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Sistema de Inventario', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuraciones/')),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('impuesto', models.DecimalField(decimal_places=2, default=17.0, max_digits=5, verbose_name='Impuesto IVA')),
                ('precio1', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Precio Venta Publico')),
                ('precio2', models.DecimalField(decimal_places=2, default=35.0, max_digits=5, verbose_name='Precio Venta Mayorista')),
                ('precio3', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Precio Venta Distribuidor')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('idUnit', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'units',
            },
        ),
    ]
